# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

meal1 = Meal.create(name:"Pad Thai",image:"https://www.cookingclassy.com/wp-content/uploads/2019/03/pad-thai-1.jpg",kind:"Thai noodle dinner",description:"is made with rehydrated dried rice noodles which are stir fried with eggs and chopped firm tofu, flavored with tamarind pulp, fish sauce, dried shrimp, garlic or shallots, red chili pepper and palm sugar, and served with lime wedges and often chopped roasted peanuts.")
meal2 = Meal.create(name:"Jamaican oxtails with rice and peas",image:"https://i.pinimg.com/originals/a2/2e/f2/a22ef20fb677a5c91af539193bbafd1d.jpg",kind:"Jamaican dinner plate",description:"Oxtails taste like good strong beef.Deep and rich and satisfying.")
meal3 = Meal.create(name:"kao soi",image:"https://www.seriouseats.com/recipes/images/2014/09/20140707-small-house-thai-cooking-school-khao-soi-10-1500x1125.jpg",kind:"Thai dinner plate",description:"Khao soi or khao soy is a Chin Haw dish served widely in Myanmar, Laos and northern Thailand.")
meal4 = Meal.create(name:"Lomo Saltado",image:"https://www.eatperu.com/wp-content/uploads/2019/06/lomo-saltado-with-rice-and-cilantro-recipe.jpg",kind:"Peruvian stir fry dinner",description:"Lomo saltado is a popular, traditional Peruvian dish, a stir fry that typically combines marinated strips of sirloin with onions, tomatoes, french fries, and other ingredients; and is typically served with rice.")
meal5 = Meal.create(name:"Papa a la Huancaina",image:"https://www.196flavors.com/wp-content/uploads/2016/07/papa-a-la-huancaina-1-FP.jpg",kind:"Peruvian appetizer",description:"Papa a la huancaína is a Peruvian appetizer of boiled yellow potatoes in a spicy, creamy sauce called huancaína sauce. Although the dish's name is derived from Huancayo, a city in the Peruvian highlands, this dish is from Lima - Perú. It has become a staple of everyday and holiday cuisine throughout the country.")
meal6 = Meal.create(name:"Jerk chicken",image:"https://www.theoriginaldish.com/wp-content/uploads/2017/09/Jerk-Chicken-1-819x1024.jpg",kind:"Jamaican Jerk",description:"jerk is a style of cooking native to Jamaica, in which meat is dry-rubbed or wet marinated with a hot spice mixture called Jamaican jerk spice. Some historians believe it was originally developed by Maroons, African slaves who escaped into the wilds of Jamaica when the British captured the island from Spain in 1655.")
meal7 = Meal.create(name:"Penne alla vodka",image:"https://www.dinneratthezoo.com/wp-content/uploads/2018/07/penne-alla-vodka-5.jpg",kind:"Italian Pasta dish",description:"Penne alla vodka is a pasta dish made with vodka and penne pasta, usually made with heavy cream, crushed tomatoes, onions, and sometimes sausage, pancetta or peas. The recipe became very popular in Italy and in the United States around the 1980s, when it was also offered to discotheque customers.")
meal8 = Meal.create(name:"Chicken tikka masala",image:"https://cafedelites.com/wp-content/uploads/2018/04/Best-Chicken-Tikka-Masala-IMAGE-2.jpg",kind:"Indian chicken dinner",description:"Chicken tikka masala is a dish of chunks of roasted marinated chicken in a spiced curry sauce. The sauce is usually creamy and orange-coloured. There are multiple claims to its place of origin such as the Indian subcontinent and the United Kingdom. It is among the United Kingdom's most popular dishes.")
meal9 = Meal.create(name:"Orange Chicken",image:"https://dinnerthendessert.com/wp-content/uploads/2017/08/Panda-Express-Orange-Chicken-8-.jpg",kind:"chinese american dinner plate",description:"Orange chicken is a Chinese dish of U.S. origin.")
meal10 = Meal.create(name:"The Cheese Burger",image:"https://d1bjorv296jxfn.cloudfront.net/s3fs-public/styles/recipes_header_image/public/SRG_EasyBake_Cheeseburger_95215_copy.jpg?itok=FdVkkn7w",kind:"American beef pattie",description:"A cheeseburger is a hamburger topped with cheese. Traditionally, the slice of cheese is placed on top of the meat patty, but the burger can include variations in structure, ingredients and composition. The cheese is usually added to the cooking hamburger patty shortly before serving, which allows the cheese to melt.")
